version: 0.2
env:
  variables:
    S3_BUCKET: "webbucket360"
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing AWS CLI...
      - pip install awscli --upgrade --user
      - export PATH=$PATH:$HOME/.local/bin
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install --legacy-peer-deps
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on $(date)
      - ng build --configuration=production --aot
  post_build:
    commands:
      - aws s3 cp dist s3://${S3_BUCKET} --recursive
      - aws s3 cp --cache-control "max-age=0, no-cache, no-store, must-revalidate" ./dist/angular-hello-world/index.html s3://webbucket360/
      - aws cloudfront create-invalidation --distribution-id E34Q8PCDFGM3X4 --paths /index.html

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
  discard-paths: yes
